### ISSUE TITLE
Running "pretty" on brefphp/bref

### ISSUE THREAD

**Issue by Nyholm** [mnapoli/pretty#16]
```shell
> pretty fix
PHP CodeSniffer configuration file found, running CodeSniffer with version
ERROR: PHP CodeSniffer does not seem to be installed because the 'phpcbf' program cannot be found.
You can install it by following the instructions here: https://github.com/squizlabs/PHP_CodeSniffer#installation
> composer global require "squizlabs/php_codesniffer=*"
(successfully installed)
>  pretty fix                                           
PHP CodeSniffer configuration file found, running CodeSniffer with version
PHP_CodeSniffer version 3.4.2 (stable) by Squiz (http://www.squiz.net)

ERROR: Referenced sniff "Doctrine" does not exist

Run "phpcbf --help" for usage information

Errors were found, run 'pretty fix' to fix them.
```

I have to somehow figure out that I must run `composer global require doctrine/coding-standard`. (Or maybe there is another way?)

We are now a long way from `php-fixer fix` which was something I liked with `pretty ci`. 

Anyhow, I maybe should have opened this issue on Bref. I just wanted to share some frustration.

**Comment by mnapoli** [comment]
Hi, what is your question?

**Comment by Nyholm** [comment]
Sorry, 

I like the message saying: 
> ERROR: PHP CodeSniffer does not seem to be installed because the 'phpcbf' program cannot be found.

But the error message: 

> ERROR: Referenced sniff "Doctrine" does not exist

Does not really help me. Could one print a line that describes how to recover from that error?

**Comment by mnapoli** [comment]
OK so just to be clear there is no relation to Bref right?

The way custom standards work is that they need to register themselves.

As you can see [in the code](https://github.com/mnapoli/pretty/blob/master/pretty) pretty just runs the `phpcs` command. You would have the same issue when running the `phpcs` command directly.

> Does not really help me. Could one print a line that describes how to recover from that error?

Maybe that's an issue that should be opened in CodeSniffer itself?

If that's not the issue please explain, because this ticket is confusing and I'm not sure I understood your issue completely.

**Comment by Nyholm** [comment]
I see, you are correct. 
I should open that on the CodeSniffer repo.


Sorry if Im more confusing than normal.
