### ISSUE TITLE
Clean Way Inspiration

### ISSUE THREAD

**Issue by TomasVotruba** [mnapoli/pretty#7]
Just in case you'd like to use something else than default and not reinvent the wheel :)
https://github.com/Symplify/EasyCodingStandard#the-easiest-way-to-use-any-coding-standard

**Comment by mnapoli** [comment]
Thanks, that's interesting, maybe you could add support for it?

The detection happens here based on config files in the current directory: https://github.com/mnapoli/pretty/blob/master/pretty#L50

**Comment by TomasVotruba** [comment]
ECS is not-another-coding-standard-tool, but basically wrapper like this one. With difference, that it has single API for both tools, to make it easy to start and mantain the set, even if you don't know any of those tool in depth.

I'm not sure combining 2 wrappers wrapping same thing makes sense.

**Comment by mnapoli** [comment]
Since you are putting phpcs and php-cs-fixer config in a "proprietary" config file (`easy-coding-standard.neon`) that means running `pretty` will not work as expected with this projects. It also means (I guess) that your tool will not simply run `phpcs` or `php-cs-fixer` on a project using one of these? (like `pretty` does)

As such, to me it's a clever and very interesting wrapper, but it's still another checker. It is not a universal command.

So adding support in `pretty` so that people don't have to figure out which tool is needed to run in every project makes sense.

If you take it the other way around nobody will need to figure out whether you need to use `pretty` or something else: you don't use `pretty` for coding style, you just use it to abstract the actual tool that needs to be run.

Hope that makes more sense?

**Comment by mnapoli** [comment]
Mmh said another way:

- your tool is a wrapper for the configuration
- this tool is a wrapper for the usage

**Comment by TomasVotruba** [comment]
Exactly, they overlap a lot though. I just wanted to drop an inspiration, in case you or anyone would like to solve problem that was already solved.
